apiVersion: v1
kind: Namespace
metadata:
  name: secplay

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground-user-readonlyfs
  namespace: secplay
  labels:
    app: security-playground-readonlyfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-playground-readonlyfs
  template:
    metadata:
      labels:
        app: security-playground-readonlyfs
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      volumes:
      - name: temp-volume
        emptyDir:
          sizeLimit: 50Mi
      containers:
      - name: security-playground-readonlyfs
        image: ghcr.io/andrewd-sysdig/security-playground:user-latest
        volumeMounts:
        - mountPath: /usr/tmp
          name: temp-volume
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-playground-readonlyfs
  name: security-playground-readonlyfs-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: security-playground-readonlyfs
  type: LoadBalancer


