apiVersion: v1
kind: Namespace
metadata:
  name: secplay

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground-user
  namespace: secplay
  labels:
    app: security-playground-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-playground-user
  template:
    metadata:
      labels:
        app: security-playground-user
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      containers:
      - name: security-playground-user
        image: fernii/security-playground:2.0-user
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-playground-user
  name: security-playground-user-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: security-playground-user
  type: LoadBalancer