apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground
  labels:
    app: security-playground
  namespace: security-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-playground
  template:
    metadata:
      labels:
        app: security-playground
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      dnsPolicy: Default
      containers:
      - name: security-playground
        image: ghcr.io/aaronm-sysdig/security-playground:latest
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-playground
  name: secplay
  namespace: security-playground
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30100
  selector:
    app: security-playground
  type: NodePort
